"""Definitions of keyword-based signal rules, source boosts and thresholds."""
from typing import Dict, List

SIGNAL_RULES: Dict[str, Dict[str, List[str]]] = {
    "expansion": {
        "primary": [
            "expanding",
            "expansion plan",
            "new plant",
            "new factory",
            "new facility",
            "plant expansion",
            "factory expansion",
            "capacity expansion",
            "capacity increase",
            "capacity addition",
            "greenfield",
            "brownfield",
            "new unit",
            "new production line",
            "production expansion",
            "scale up",
            "new site",
            "manufacturing expansion",
            "expand production",
            "expand capacity",
        ],
        "secondary": [
            "invest",
            "investment",
            "crore",
            "billion",
            "launch",
            "construction",
            "south india",
            "north india",
            "location",
            "units",
            "phase",
            "quarter",
            "announced",
            "operational",
            "commissioned",
            "project",
        ],
    },
    "sustainability": {
        "primary": [
            "net zero",
            "carbon neutral",
            "carbon neutrality",
            "bio-based",
            "renewable energy",
            "zero emission",
            "circular economy",
            "esg goal",
            "green manufacturing",
            "sustainable sourcing",
            "carbon footprint reduction",
            "decarbonization",
            "low-carbon",
            "climate target",
        ],
        "secondary": [
            "green",
            "solar",
            "recycl",
            "emission",
            "climate",
            "scope 1",
            "scope 2",
            "scope 3",
            "eco-friendly",
            "biodiversity",
            "water conservation",
            "waste reduction",
            "sustainable",
        ],
    },
    "capex_investment": {
        "primary": [
            "capital expenditure",
            "capex",
            "capital investment",
            "capital spending",
            "infrastructure investment",
            "fixed asset investment",
            "plant investment",
            "capacity investment",
            "capex plan",
            "spending plan",
            "expenditure plan",
        ],
        "secondary": [
            "crore",
            "million",
            "billion",
            "allocat",
            "budget",
            "spend",
            "fund",
            "investment",
            "fiscal",
            "fy",
        ],
    },
    "supply_chain": {
        "primary": [
            "supplier diversification",
            "new supplier",
            "supply chain",
            "vendor change",
            "procurement strategy",
            "local sourcing",
            "import substitution",
            "backward integration",
            "raw material sourcing",
            "inventory optimization",
            "distribution network",
            "logistics optimization",
            "supplier network",
        ],
        "secondary": [
            "supplier",
            "vendor",
            "material",
            "logistics",
            "procurement",
            "sourcing",
            "warehouse",
            "transport",
            "freight",
            "distribution",
        ],
    },
    "digital_transformation": {
        "primary": [
            "digital transformation",
            "ai adoption",
            "artificial intelligence",
            "machine learning",
            "cloud migration",
            "erp implementation",
            "automation",
            "industry 4.0",
            "iot",
            "data analytics platform",
            "digitalization",
            "digitization",
        ],
        "secondary": [
            "technology",
            "digital",
            "software",
            "data",
            "analytics",
            "platform",
            "ai",
            "ml",
            "automation roadmap",
        ],
    },
    "competitor_activity": {
        "primary": [
            "acquisition",
            "merger",
            "joint venture",
            "market share",
            "strategic alliance",
            "partnership announcement",
            "takeover",
            "new market entry",
            "collaboration",
            "deal",
        ],
        "secondary": [
            "market",
            "deal",
            "agreement",
            "collaboration",
            "compete",
            "partnership",
            "alliance",
        ],
    },
    "hiring": {
        "primary": [
            "hiring",
            "recruitment",
            "new roles",
            "headcount increase",
            "workforce expansion",
            "talent acquisition",
            "mass hiring",
            "open positions",
            "job openings",
            "career opportunities",
            "join our team",
        ],
        "secondary": [
            "engineer",
            "manager",
            "director",
            "team",
            "employee",
            "staff",
            "head",
            "specialist",
            "associate",
            "intern",
        ],
    },
}

SOURCE_BOOST: Dict[str, float] = {
    "annual_report": 0.10,
    "esg": 0.08,
    "news": 0.05,
    "hiring": 0.05,
}

THRESHOLDS = {
    "HIGH": 0.75,
    "LOW": 0.40,
}
