"""LangChain-coordinated signal analysis orchestration."""

from __future__ import annotations

import asyncio
import time
from typing import Any, Dict, List, Optional

try:
    from langchain_core.runnables import RunnableLambda, RunnableParallel
except Exception:  # pragma: no cover - optional orchestration dependency
    RunnableLambda = None
    RunnableParallel = None

from .account_summary import generate_account_summary
from .competitive_signal_agent import analyze_competitive_signals
from .financial_signal_agent import analyze_financial_signals
from .hiring_signal_agent import analyze_hiring_signals
from .llm_client import llm_enabled
from .market_signal_agent import analyze_market_signals
from .signal_utils import dedupe_signals, normalize_signal, utc_now_iso


def _run_with_langchain(
    company_name: str,
    account_id: str,
    raw_sources: Dict[str, str],
    use_llm: bool = True,
) -> Dict[str, Any]:
    """Run analysis agents through LangChain RunnableParallel when available."""
    if RunnableLambda is None or RunnableParallel is None:
        return {
            "financial": analyze_financial_signals(company_name, account_id, raw_sources.get("annual_report", ""), use_llm),
            "market": analyze_market_signals(company_name, account_id, raw_sources, use_llm),
            "hiring": analyze_hiring_signals(company_name, account_id, raw_sources.get("hiring", ""), use_llm),
            "competitive": analyze_competitive_signals(company_name, account_id, raw_sources, use_llm),
        }

    chain = RunnableParallel(
        financial=RunnableLambda(
            lambda _: analyze_financial_signals(company_name, account_id, raw_sources.get("annual_report", ""), use_llm)
        ),
        market=RunnableLambda(lambda _: analyze_market_signals(company_name, account_id, raw_sources, use_llm)),
        hiring=RunnableLambda(lambda _: analyze_hiring_signals(company_name, account_id, raw_sources.get("hiring", ""), use_llm)),
        competitive=RunnableLambda(lambda _: analyze_competitive_signals(company_name, account_id, raw_sources, use_llm)),
    )
    return chain.invoke({})


def _legacy_rule_signal_to_dashboard(
    company_name: str,
    account_id: str,
    rule_signal: Dict[str, Any],
    detected_at: str,
) -> Dict[str, Any]:
    source_type = rule_signal.get("source_type") or "public_mentions"
    category = {
        "annual_report": "financial",
        "hiring": "hiring",
        "news": "market",
        "esg": "market",
    }.get(source_type, "market")
    return normalize_signal(
        {
            "signal_type": rule_signal.get("signal_type") or "business_signal",
            "title": rule_signal.get("description") or rule_signal.get("raw_snippet") or "Business signal",
            "description": rule_signal.get("description") or rule_signal.get("raw_snippet") or "",
            "evidence": rule_signal.get("raw_snippet") or rule_signal.get("description") or "",
            "confidence_score": rule_signal.get("confidence", 0.55),
            "relevance_score": 60,
            "reasoning": "Fallback signal generated by the rule engine.",
        },
        {
            "account_id": account_id,
            "company_name": company_name,
            "agent": "rule_engine_fallback",
            "category": category,
            "source_type": source_type,
            "detected_at": detected_at,
            "classification": "monitor",
        },
    )


async def run_signal_analysis(
    company_name: str,
    account_id: str,
    raw_sources: Dict[str, str],
    company_profile: Optional[Dict[str, Any]] = None,
    rule_signals: Optional[List[Dict[str, Any]]] = None,
    timeout_seconds: int = 50,
) -> Dict[str, Any]:
    """Run all signal analysis agents and return account intelligence.

    This is the Step 2 agent layer: domain agents produce classified,
    timestamped, recency/relevance-scored signals, then the summary layer
    renders account intelligence for the dashboard/API response.
    """
    started = time.perf_counter()
    detected_at = utc_now_iso()
    raw_sources = raw_sources or {}
    rule_signals = rule_signals or []

    try:
        agent_results = await asyncio.wait_for(
            asyncio.to_thread(_run_with_langchain, company_name, account_id, raw_sources, True),
            timeout=timeout_seconds,
        )
        orchestration_status = "completed"
    except asyncio.TimeoutError:
        print(f"run_signal_analysis timeout after {timeout_seconds}s")
        agent_results = await asyncio.to_thread(_run_with_langchain, company_name, account_id, raw_sources, False)
        orchestration_status = "timeout_fallback"
    except Exception as exc:
        print(f"run_signal_analysis error: {exc}")
        agent_results = await asyncio.to_thread(_run_with_langchain, company_name, account_id, raw_sources, False)
        orchestration_status = "fallback_after_error"

    signals: List[Dict[str, Any]] = []
    for result in agent_results.values() if isinstance(agent_results, dict) else []:
        if isinstance(result, dict) and isinstance(result.get("signals"), list):
            signals.extend(signal for signal in result["signals"] if isinstance(signal, dict))

    if not signals and rule_signals:
        signals = [
            _legacy_rule_signal_to_dashboard(company_name, account_id, signal, detected_at)
            for signal in rule_signals[:12]
            if isinstance(signal, dict)
        ]

    signals = dedupe_signals(signals)
    summary_use_llm = (
        llm_enabled()
        and orchestration_status == "completed"
        and (time.perf_counter() - started) < max(0, timeout_seconds - 8)
    )
    summary = generate_account_summary(company_name, signals, use_llm=summary_use_llm)
    elapsed_ms = round((time.perf_counter() - started) * 1000, 2)

    return {
        "account_id": account_id,
        "company_name": company_name,
        "status": orchestration_status,
        "generated_at": detected_at,
        "processing_time_ms": elapsed_ms,
        "target_latency_seconds": {"min": 30, "max": 60},
        "llm_enabled": llm_enabled(),
        "dashboard_ready": True,
        "signal_count": len(signals),
        "signals": signals,
        "summary": summary,
        "agent_results": agent_results,
        "company_profile": company_profile or {},
        "source_char_counts": {source: len(text or "") for source, text in raw_sources.items()},
    }
